language: objective-c
osx_image: xcode8
xcode_project: TagListViewDemo.xcodeproj
xcode_scheme: TagListViewDemo
xcode_sdk:
  - iphonesimulator9.0
script:
  - xctool -project TagListViewDemo.xcodeproj -scheme TagListViewDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
